"""Initial migration.

Revision ID: e7cb0c576dc3
Revises: 
Create Date: 2021-01-31 19:13:49.544050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7cb0c576dc3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('english', sa.String(), nullable=True),
    sa.Column('german', sa.String(), nullable=True),
    sa.Column('part_of_speech', sa.String(), nullable=True),
    sa.Column('last_viewed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_id'), 'card', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_card_id'), table_name='card')
    op.drop_table('card')
    # ### end Alembic commands ###
